# Vectores

La descripción matemática de ciertos fenómenos del mundo real requiere de una colección de números. Por ejemplo, un lugar sobre la superficie de la tierra es descrito por dos números, latitud y longitud. Para especificar una posición por encima del suelo sobre la tierra se requiere un tercer número, la altitud. Para describir el estado de un gas tenemos que especificar su densidad y temperatura; si es una mezcla de gases como el oxígeno y nitrógeno, tenemos que especificar su proporción. Tales situaciones se abstraen en el concepto de un vector.

## Definicion

Un vector es una lista finita ordenada de números. Los vectores generalmente se escriben de forma vertical u horizontal rodeados por corchetes,

$$\left[\begin{array}{c}
1.1\\
0.0\\
3.6\\
7.2
\end{array}\right]\quad\left[\begin{array}{rrrr}
1.1 & 0.0 & 3.6 & 7.2\end{array}\right].$$

También se pueden escribir como números separados por comas y rodeados de paréntesis. En este estilo de notación, el vector de arriba se escribe como

$$(1.1, 0.0, 3.6, 7.2)$$

Los elementos (o entradas, coeficientes, componentes) de un vector son los valores en el arreglo. El tamaño (también llamado dimensión) del vector es el número de
elementos que contiene. El vector de arriba, por ejemplo, tiene tamaño cuatro; su tercera entrada
es 3.6. Un vector de tamaño $n$ se llama $n-$vector. Se considera que un $1-$vector es igual que un número, es decir, no distinguimos entre el $1-$vector $[ 1.3 ]$ y el
número $1.3$.
y muchos muchos mas. $(\mathbb{R}^2)$.

En Python, puede crear una lista usando corchetes como $[1,2,3]$. Esto se llama una "lista de Python" y NO es un vector en la forma en que lo pensamos matemáticamente. Es simplemente una colección ordenada de objetos. Para construir vectores matemáticos en Python, necesitamos usar matrices numpy con np.array(). Por ejemplo, el vector anterior sería:

In [1]:
import sympy
from sympy.abc import x, a, b, c
from sympy import integrate, init_printing
init_printing(use_latex="mathjax")

In [2]:
import numpy as np
u = np.array([1.1,0.0,3.6,7.2])
print(u)

[1.1 0.  3.6 7.2]


Otra manera de crear vectores es con el comando
```
list
```
Como veremos en python se pueden crear listas de números aleatorios con la longitud que deseemos.


In [3]:
import numpy as np
random_list = list(np.random.choice(range(256), size=3))
print(random_list)

[np.int64(154), np.int64(252), np.int64(136)]


Uno de los usos mas comunes en vectores son los colores. RGB significa rojo, verde y azul. Juntos representan el espectro de colores en el mundo digital. Al combinarse estos colores se pueden generar todos los colores donde cada uno de ellos tiene 8 bits, lo que tiene como significado que pueden ser representados por un entero de 0 a 255.





También podemos es importante saber longitud de los vectores. Esto es util cuando queremos saber si se pueden realizar operaciones con los vectores.

In [4]:
import numpy as np
dimension_list = [1.65, 1.82, 1.23, 1.56, 1.72, 1.98, 1.65]
np_dimension_list = np.array(dimension_list)
print(len(np_dimension_list))

7


Sobre las listas podemos usar una variedad de métodos que nos permitiran encontrar elementos de dentro de las listas o relaizar operaciones con sus elementos.

In [5]:
np_dimension_list.max()

# min(): Obtener el valor menor dentro del vector
np_dimension_list.min()

# sort(): ordena los elementos del vector de mayor a menor
np_dimension_list.sort()

# round(): Redondea los valores del vector
np_dimension_list.round()

# sum(): Nos devuelve la suma de todos los valores del vector
np_dimension_list.sum()

# put():Inserta un nuevo elemento en la matriz en la posición especificada
np_dimension_list.put(-1, 1.79)

# Operaciones con vectores

Las operaciones y sus propiedades son las mismas que usted conoce en los números reales. La diferencia radica en el tipo de objetos que usted está operando. En particular, vamos a introducir las operaciones de SUMA  y PRODUCTO POR UN ESCALAR para cualquier par de vectores $\mathbf{u}=(u_1,u_2,...u_n)$ y $\mathbf{v}=(v_1,v_2,...,v_n)$:

**SUMA:** 

$$ \left[\begin{array}{c}
u_1\\
u_2\\
\vdots\\
u_n
\end{array}\right]+\left[\begin{array}{c}
v_1\\
v_2\\
\vdots\\
v_n
\end{array}\right]=\left[\begin{array}{c}
u_1+v_1\\
u_2+v_2\\
\vdots\\
u_n+v_n
\end{array}\right]$$

un ejemplo de la suma entre vectores en python.


In [6]:
import numpy as np

np_list1 = np.array([45, 65, 23 ,4 ,34])
np_list2 = np.array([6, 32, 8, 82, 77])

np_sum = np_list1 + np_list2

print(np_sum)

[ 51  97  31  86 111]


**PRODUCTO POR ESCALAR:**

$$ 
c\left[\begin{array}{c}
u_1\\
u_2\\
\vdots\\
u_n
\end{array}\right]=\left[\begin{array}{c}
c u_1\\
c u_2\\
\vdots\\
c u_n
\end{array}\right]
$$


In [7]:
np_product = 4 * np_list1

print(np_product)

[180 260  92  16 136]


**PRODUCTO PUNTO:**

Producto punto: Para cualquier par de $n-$vectores $\mathbf{u}$ y $\mathbf{v}$ se tiene que

$$  \left[\begin{array}{c}
u_1\\
u_2\\
\vdots\\
u_n
\end{array}\right]\cdotp\left[\begin{array}{c}
v_1\\
v_2\\
\vdots\\
v_n
\end{array}\right]=u_1v_1+u_2v_2+...+u_nv_n=\sum_{i=1}^n u_iv_i$$

en python se pueden realizar porducto punto entre vectores de la siguiente forma

In [8]:
dot_product = np_list1 @ np_list2
print(dot_product)

5480


In [9]:
dot_product_1=np.dot(np_list1,np_list2)
print(dot_product_1)

5480


**MAGNITUD:**

Finalmente, debemos mencionar que geométricamente es fácil encontrar la magnitud de un vector utilizando el teorema de Pitágoras. La magnitud del vector $\mathbf{u}$ se denota con $||\cdot||$ y se calcula como sigue:

$$||\mathbf{u}||  = \sqrt{u_1^2+u_2^2+...+u_n^2}= \sqrt{\mathbf{u}\cdot\mathbf{u}}$$

In [10]:
from numpy import array
from numpy.linalg import norm
arr = array([1, 2, 3, 4, 5])
print(arr)
norm_l2 = norm(arr)
print(norm_l2)

[1 2 3 4 5]
7.416198487095663


**NOTA:**

En particular, se puede estudiar el concepto de **combinación lineal** que involucra las dos operaciones anteriores. Una **combinación lineal** de los vectores $\mathbf{u}=(u_1,u_2,...u_n)$ y $\mathbf{v}=(v_1,v_2,...,v_n)$ se expresa como

$$a \mathbf{u}+ b \mathbf{v},\qquad a,b\in \mathbb{R}$$

Geometricamente podemos observar como se comporta una combinación lineal.



In [11]:
#@title  { display-mode: "form" }

import IPython.display as IP

iframe = IP.IFrame(
  src="https://www.geogebra.org/classic/xgqzppfx",
  width="1020px",
  height="480px"
  )

IP.display_html(iframe)