# Operaciones con matrices

## Producto de una matriz por un escalar






La multiplicación escalar de matrices se define de manera similar a la de vectores, y es hecha multiplicando cada elemento de la matriz por el escalar.

In [1]:
import sys
import numpy as np

array = np.arange(10)
np.set_printoptions(threshold=sys.maxsize)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
import sys
import numpy as np
matriz = np.array([[2, 4], [5, -6]])
np.set_printoptions(threshold=sys.maxsize)
print(matriz)

[[ 2  4]
 [ 5 -6]]


In [3]:
c=5
cmatriz = np.multiply(matriz,c)
cmatriz
np.set_printoptions(threshold=sys.maxsize)
print(cmatriz)

[[ 10  20]
 [ 25 -30]]


## Suma de matrices



Similarmente la suma de matrices del mismo tamaño se hace componente a componente, esto es, si $A=(A)_{ij}$ y $B=(B)_{ij}$ entonces $$C=(C)_{ij}=(A)_{ij}+(B)_{ij} $$




In [4]:
S = matriz + cmatriz
print(S)


[[ 12  24]
 [ 30 -36]]


## Producto matriz-vector



Si A es una matriz $m\times n$ y $x$ es un $n-$vector, entonces el producto matriz-vector $y = Ax$ es el $m-$vector $y$ con elementos

$$ y_i = \sum_{k=1}^n A_{ik}x_k=A_{i1}x_1+...+A_{in}x_n.,\quad i=1,...,m.$$



In [5]:
import numpy as np
vector_1 = [1,0,1,2,4]
vector_2 = [0,1,0,3,2]
vector_3 = [2,4,3,1,0]
vector_4 = [2,1,0,1,3]
matriz2 = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz2)

[[1 0 1 2 4]
 [0 1 0 3 2]
 [2 4 3 1 0]
 [2 1 0 1 3]]


In [6]:
vector = [0,2,3,5,1]
matriz_resultado = matriz2.dot(vector)
print(matriz_resultado)

[17 19 22 10]


In [7]:
matriz_producto = np.matmul(matriz2,vector)

## Producto matriz-matriz



Es posible multiplicar dos matrices $A$ y $B$ usando la multiplicación de matrices. siempre que sus dimensiones sean compatibles, lo que significa que elnúmero de columnas de $A$ es igual al número de filas de $B$. Supongamos que $A$ y $B$ son compatibles, por ejemplo, $A$ tiene tamaño $m\times p$ y $B$ tiene tamaño $p\times n$. Entonces la matriz del producto $C = AB$ es la matriz $m\times n$ con elementos

$$C_{ij}=\sum_{k=1}^? A_{ik}B_{kj}=A_{i1}B_{1j}+...+A_{ip}B_{pj}.,\quad i=1,...,m,\quad j=1,...,n.$$

In [8]:
import numpy as np
vector_1 = [1,0,1,2]
vector_2 = [0,1,0,3]
vector_3 = [2,4,3,1]
vector_4 = [2,1,0,1]
matriz_1 = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz_1)

[[1 0 1 2]
 [0 1 0 3]
 [2 4 3 1]
 [2 1 0 1]]


In [9]:
import numpy as np
vector_1 = [1,0,1,2,4]
vector_2 = [0,1,0,3,2]
vector_3 = [2,4,3,1,0]
vector_4 = [2,1,0,1,3]
matriz_2 = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz_2)

[[1 0 1 2 4]
 [0 1 0 3 2]
 [2 4 3 1 0]
 [2 1 0 1 3]]


In [10]:
matriz_producto = np.matmul(matriz_1,matriz_2)
print(matriz_producto)

[[ 7  6  4  5 10]
 [ 6  4  0  6 11]
 [10 17 11 20 19]
 [ 4  2  2  8 13]]


También se puede calcular el producto de matrices con el comando

```
A.dot(B)
```
* *$A$* es una matriz ${nxm}$
* *$B$* es una matriz ${mxp}$


## Matriz Idempotente

Una matriz idempotente es una matriz cuadrada cuyo producto por sí misma es igual a ella misma:
$$A^2 =A⋅A=A$$

In [11]:
import numpy as np
A = np.matrix([[2, -3, -5],[-1, 4, 5],[1, -3, -4]])
B=A.dot(A)
B

matrix([[ 2, -3, -5],
        [-1,  4,  5],
        [ 1, -3, -4]])

## Matriz inversa



La matriz inversa de una matriz $A_{nxn}$ es una matriz cuadrada, representada por $A^{-1}_{nxn}$.

In [12]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
matriz_inv = np.linalg.inv(matriz)
print(matriz_inv)

[[1.         0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.        ]
 [0.         0.         0.2        0.         0.        ]
 [0.         0.         0.         0.14285714 0.        ]
 [0.         0.         0.         0.         0.09090909]]


Se dice que $A^{-1}$ es la inversa de otra matriz cuadrada $A$ cuando el producto de ambas matrices es la matriz identidad.

In [13]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
matriz_inv = np.linalg.inv(matriz)
print(matriz.dot(matriz_inv))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Otras operaciones

## Operaciones Matriz traspuesta

Sean $A$ y $B$ matrices $mxn$ entonces:

* $(A+B)^T = A^T + B^T$
* $(\alpha A)^T =  \alpha Α^T$
* $(AB)^T = B^TA^T$

## Operaciones con inversas

Sean $A$ y $B$ dos matrices invertibles entonces:
* $(AB)^{-1}=B^{-1}A^{-1}$
* $(A^T)^{-1}= (A^{-1})^{T}$
* $(A^{-1})^{-1}= A$
